### PR TITLE
fix scrolling on large screens

### PR DESCRIPTION
**Pull request by SupriyaAdep**
# Related Issue
- Scroll appears on larger screens
- https://agora.clickup.com/t/8556478/APP-1248

# Proposed changes/Fix
- Remove margins

# Checklist
- [x] Tested on local/dev branch for all major platforms (Android, IOS, Desktop, Web).
- [x] No commented out code
- [x] Is any third party library, service used
- [x] Tests
- [ ] If this change requires updates outside of the code, like updates in core, react-ui-kit, RTM/RTC configure.

# Dependent PRs 
- NA

# Screenshots

Scrolling before
----------------------------
https://user-images.githubusercontent.com/22396308/164227137-3bc897ca-1f72-4ae1-b669-2ddf43821730.mov

Scrolling after
-----------------

https://user-images.githubusercontent.com/22396308/164227176-17de16bf-61da-458d-b555-cc2a0f57e146.mov

### CODE REVIEW

**Review by nitte93 — CHANGES_REQUESTED** [review]
Please add before and after shots

**Comment by SupriyaAdep** [comment]
@nitte93, I have added before and after shots

**Comment by nitte93** [comment]
Can we have this raised against preprod first ?

**Comment by SupriyaAdep** [comment]
Closing this PR, as it was branched off from master and raised against master.
This was done, because preprod was unstable with 4.11.1 sdk update.
New PR https://github.com/AgoraIO-Community/app-builder-core/pull/119/files is raised against preprod.
Hence closing this PR

**Pull request closed without merging**
