### PR TITLE
Added prompts to confirm before navigation

### PR DESCRIPTION
**Pull request by Adictya**
Added confirmation prompt before following actions

WEB
- Close tab

Native
- Press leave call button
- Press hardware back button

Electron
--nil--

### CODE REVIEW

**Comment by Adictya** [comment]
Due to the following issue https://github.com/remix-run/react-router/issues/5405
We cant have the behaviour extend to web with the same component. 
Working on a way around.

**Comment by Adictya** [comment]
Tagging for visiblity @technophilic @nitte93

**Comment by nitte93** [comment]
LGTM, a suggestion would be to use a custom hook for eventhandlers 
For reference :https://usehooks.com/useEventListener/
Also, let me know if you want to discuss the implementation for 'leave call button' and ' browser back' for web

**Comment by Adictya** [comment]
Sure, I'll extend it with custom hooks

**Pull request closed without merging**
